In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a=np.array([1,2.5,3])
print(a)

[1.  2.5 3. ]


In [5]:
a=np.array([1,2.5,3,'a'])
print(a)

['1' '2.5' '3' 'a']


In [41]:
a=np.array([[1, 2],[3, 4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
# minimum dimensions
import numpy as np

a= np.array([1, 2, 3,4,5] ,ndmin=2)
print(a)

[[1 2 3 4 5]]


In [7]:
# dtype parameter
import numpy as np
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
# dtype parameter
import numpy as np
a=np.array([1.0,2.0,3.0],dtype=int)
print(a)

[1 2 3]


In [9]:
# ndarry.shape
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(a.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [10]:
a=np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
#numpy.zeros

x= np.zeros((5))
print(x)

[0. 0. 0. 0. 0.]


In [15]:
#numpy.ones

x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [17]:
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [3]:
#create two matrix
import numpy as np

matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])

In [4]:
result=np.dot(matrix1,matrix2)
print("matrix1 x matrix2:\n",result)

matrix1 x matrix2:
 [[14 30]
 [38 86]]


In [8]:
import numpy as np

matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()

[[1 3]
 [5 7]]



In [9]:
result=np.transpose(matrix1)
print(result)

[[1 5]
 [3 7]]


In [10]:
# numpy.hstack() function----

import numpy as np 
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,6,7))
print(y)
print()

[3 5 7]

[5 6 7]



In [11]:
print(np.hstack((x,y)))

[3 5 7 5 6 7]


In [15]:
import numpy as np
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.hstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3 5]
 [5 7]
 [7 9]]


In [16]:
# numpy.vstack() function----

import numpy as np 
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,6,7))
print(y)
print()
print(np.vstack((x,y)))

[3 5 7]

[5 6 7]

[[3 5 7]
 [5 6 7]]


In [19]:
import numpy as np
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
print(np.vstack((x,y)))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]

[[3]
 [5]
 [7]
 [5]
 [7]
 [9]]


In [20]:
# an array of evenly spaced numbers
import numpy as np 
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
# this is one dim array
import numpy as np
a=np.arange(24)
a.ndim

1

In [22]:
import numpy as np
x=np.arange(5, dtype= float)
print(x)

[0. 1. 2. 3. 4.]


In [25]:
import numpy as np
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [26]:
import numpy as np
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [29]:
#endpoint set to false 
import numpy as np
x=np.linspace(10,20, 5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [31]:
#find retstep value 
import numpy as np

x=np.linspace(1,2,5, retstep=True)
print(x)
              

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [32]:
a=np.array([[3,3,2],[6,9,4],[5,5,8]])
a

array([[3, 3, 2],
       [6, 9, 4],
       [5, 5, 8]])

In [33]:
np.sum(a)

45

In [34]:
np.sum(a,axis=0)

array([14, 17, 14])

In [35]:
np.sum(a,axis=1)

array([ 8, 19, 18])

In [36]:
np.min(a)

2

In [37]:
np.max(a)

9

In [38]:
np.min(a,axis=1)

array([2, 4, 5])

In [39]:
np.max(a,axis=0)

array([6, 9, 8])

In [40]:
np.max(a,axis=0)

array([6, 9, 8])

In [2]:
# shallow and deep copy

x=[1,"2",3,4,5]
x1=x
print(x1)
x1[2]=100
print(x1)

[1, '2', 3, 4, 5]
[1, '2', 100, 4, 5]


In [5]:
x2=x.copy()
x2[1]=100
x2

[1, 100, 100, 4, 5]

In [6]:
l=[[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [7]:
l2=l.copy()
l2

[[1, 2, 3], [4, 5, 6]]

In [8]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 5, 6]]

In [9]:
l

[[1, 2, 100], [4, 5, 6]]

In [15]:
import copy
l=[[1,2,3],[4,5,6]]
l2=copy.deepcopy(l)
l2

[[1, 2, 3], [4, 5, 6]]

In [16]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 5, 6]]

In [17]:
l

[[1, 2, 3], [4, 5, 6]]

In [27]:
# random number generation 

import numpy as np
randomnumber=np.random.randint(0,10)
print(randomnumber)

5


In [30]:
from numpy import random
randomnumber =random.randint(0,10)
print(randomnumber)

9


In [34]:
import numpy as np
randomnumber=np.random.rand()
print(randomnumber)

0.022549007610759286


In [41]:
integer_array=np.random.randint(0,10,5)
print("1D Random Integer Array;\n",integer_array)

1D Random Integer Array;
 [3 8 6 0 7]


In [43]:
float_array=np.random.rand(5)
print("\n 1D Random Array :\n",float_array)


 1D Random Array :
 [0.96943807 0.27781199 0.827353   0.33864973 0.2190089 ]


In [44]:
result=np.random.randint(0,10,(3,4))
print("\n2D Random Integer Array:\n",result)


2D Random Integer Array:
 [[3 9 5 8]
 [5 9 5 5]
 [0 9 8 5]]


In [51]:
array1=np.array([1,2,3,4,5])

random_choice=np.random.choice(array1)
print(random_choice)

1


In [52]:
np.random.randn(5,5)

array([[-0.63564422, -0.95244882, -0.84838857,  0.35773762, -1.35114076],
       [ 1.62807524,  2.11980979,  0.5168402 ,  0.9545346 ,  0.83706493],
       [ 0.04562354, -1.05317095, -0.61922226,  1.32440858, -0.40671986],
       [ 1.22453322,  1.06493714,  2.17947241,  0.03620888,  0.47904917],
       [-0.28239421,  0.42761217, -0.4168558 , -0.87481256,  1.0772019 ]])

In [53]:
import numpy as np
from numpy.random import randint as ri


In [57]:
np.random.seed(109)
ri(1,100,(5,6))

array([[ 7, 14, 16, 76, 34,  5],
       [64, 43, 58, 52, 17,  6],
       [63, 86, 23, 65, 53, 54],
       [73, 49,  8, 14, 61, 12],
       [14, 53, 39, 66, 70, 53]])

In [61]:
np.random.seed(565)
m=ri(1,100,25).reshape(5,5)

In [62]:
m

array([[ 5, 46, 63, 14, 70],
       [17,  2,  2, 11, 31],
       [67, 46,  4, 55, 94],
       [62, 73, 63, 81, 90],
       [72, 50, 68, 46, 37]])

In [63]:
np.sort(m)

array([[ 5, 14, 46, 63, 70],
       [ 2,  2, 11, 17, 31],
       [ 4, 46, 55, 67, 94],
       [62, 63, 73, 81, 90],
       [37, 46, 50, 68, 72]])

In [64]:
np.sort(m, axis=0)

array([[ 5,  2,  2, 11, 31],
       [17, 46,  4, 14, 37],
       [62, 46, 63, 46, 70],
       [67, 50, 63, 55, 90],
       [72, 73, 68, 81, 94]])

In [65]:
a=ri(1,100,30)
b=a.reshape(6,5)
b

array([[73, 86, 60, 91, 43],
       [97, 63, 63, 79, 43],
       [12, 16, 94, 56, 50],
       [61, 82, 17,  2, 89],
       [82, 69, 79, 51, 64],
       [14, 49, 52, 67, 83]])

In [66]:
a

array([73, 86, 60, 91, 43, 97, 63, 63, 79, 43, 12, 16, 94, 56, 50, 61, 82,
       17,  2, 89, 82, 69, 79, 51, 64, 14, 49, 52, 67, 83])

In [68]:
a.max()

97

In [70]:
a.argmax()

5

In [71]:
x=[121,2321,34,45,56,65]
a=np.array(x)
a.argsort()

array([2, 3, 4, 5, 0, 1], dtype=int64)

In [72]:
b.argmax()

5

In [73]:
b.argmax(axis=0)

array([1, 0, 2, 0, 3], dtype=int64)

In [74]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [75]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [76]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
a[a%2 !=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [80]:
a[a==5]

array([5])

In [81]:
a[a<5]

array([1, 2, 3, 4])

In [83]:
a[a%2 !=0]=0

In [84]:
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,2])
print(a)

[1 2 3 4 5 2]


In [4]:
a.ndim

1

In [5]:
a.shape

(6,)

In [6]:
x=np.where(a==2)
x

(array([1, 5], dtype=int64),)

In [7]:
np.where(a==3)

(array([2], dtype=int64),)

In [8]:
b=np.array([1,2,3,4,5,6])
print(b)

[1 2 3 4 5 6]


In [9]:
np.where(b<4)

(array([0, 1, 2], dtype=int64),)

In [10]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# even number
np.where(x%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [12]:
#odd number
np.where(x%2!=0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [16]:
#searchshorted
x=np.array([1,2,3,4,5,6,7,9,10,12,34,40])
print(x)

[ 1  2  3  4  5  6  7  9 10 12 34 40]


In [18]:
np.searchsorted(x,8)

7

In [20]:
x=np.array([[1,2,3,4,5],[12,23,34,55,76],[65,43,21,32,54],[8,7,6,5,4],[98,87,65,78,67]])
print(x)

[[ 1  2  3  4  5]
 [12 23 34 55 76]
 [65 43 21 32 54]
 [ 8  7  6  5  4]
 [98 87 65 78 67]]


In [21]:
x[1:3,1:3]

array([[23, 34],
       [43, 21]])

In [23]:
x[2:4,2:4]

array([[21, 32],
       [ 6,  5]])

In [25]:
x[3:,1:3]

array([[ 7,  6],
       [87, 65]])

In [26]:
#comparison b/w list and array
import sys
import time 



sys.getsizeof(100)

28

In [29]:
l=range(200000)
print(sys.getsizeof(4)*len(l))

5600000


In [30]:
import numpy as np
a=np.arange(200000)
print(a.itemsize)
print()

print(a.itemsize*len(a))

4

800000


In [31]:
#fast

In [34]:
a1=range(1000000)
b1=range(1000000)

start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken :",(time.time()-start)*1000)

time taken : 140.64955711364746


In [35]:
a2=np.arange(1000000)
b2=np.arange(1000000)

start=time.time()
c2=a2+b2
print("time taken by array:",(time.time()-start)*1000)

time taken by array: 0.0


In [36]:
n1=np.arange(100)
n2=np.arange(100)
n1*n2


array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [38]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
list (range(5))

[0, 1, 2, 3, 4]

In [41]:
a.shape

(24,)

In [42]:
b=a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [43]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[6,7]])



<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
b

array([[5, 6],
       [6, 7]])

In [51]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7]])

In [52]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 6, 7]])

In [53]:
a=np.arange(12)
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [54]:
a=np.array([[1,2,3],[4,5,6]])
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])